---
- name: Learning to use the debug module
  hosts: planet_express

  vars:
    day: Wednesday

  tasks:
  - name: Print a basic message to the screen
    debug:
      msg: This is our first debug message

  - name: Print out default IPv4 
    debug:
      var: ansible_default_ipv4
      verbosity: 3

  - name: Print out the IPv4 address
    debug:
      msg: "The IP address of {{ inventory_hostname }} is {{ ansible_default_ipv4.address }}"

  - name: Print out the day
    debug:
      var: day

  - name: Using a shell command to register a result
    shell: ls /tmp
    register: my_files

  - name: Print out the result from the previous task
    debug:
      msg: "The /tmp directory has {{ my_files.stdout_lines }} in it"  
