---
- hosts: localhost
  vars_prompt:
    - name: "name"
      prompt: "what is your name?"
      private: false
      #encrypt: sha512_crypt
      salt: 7
    - name: "quest"
      prompt: "what is your quest?"
    - name: "favcolor"
      prompt: "what is your favorite color?"

  tasks:
    - debug:
        msg: "Welcome! Your name is {{ name }}, Your quest is {{ quest }} and your favorite color is {{ favcolor }}"
