---
- name: Using vault to store and retrieve secrets
  hosts: planet_express

  vars_files:
  - topsecret.yml

  tasks:
  - name: print out the secret vars
    debug:
      msg: "{{ item }}"
    loop:
    - "{{ my_user }}"
    - "{{ my_become_pass }}"
    - "{{ my_ssh_pass }}"
